### ISSUE TITLE
Invalid authentication type

### ISSUE THREAD

**Issue by agaleski** [cvo-technologies/cakephp-twitter#8]
The last update changed _src/Webservice/Driver/Twitter.php_ to solve some test issues.

This leads to the following error when trying to use the controller example from the README:

> **Invalid authentication type CvoTechnologies/Twitter.Twitter**

I fixed it temporary for me by changing _src/Webservice/Driver/Twitter.php_ on **line 31** from:

`'type' => 'CvoTechnologies/Twitter.Twitter',`

to:

`'type' => 'oauth',`

But this should be checked and fixed. I did not have a look on the results of the tests so far.

**Comment by Marlinc** [comment]
Thank you for reporting the issue.

On what version of CakePHP is this?

**Comment by agaleski** [comment]
CakePHP : v3.3.0
PHP : 7.0.8-0ubuntu0.16.04.2

**Comment by agaleski** [comment]
And the Controller in the Readme is missing a line too:

I had to add 
        `$this->modelFactory('Endpoint', ['Muffin\Webservice\Model\EndpointRegistry', 'get']);`
before
        `$this->loadModel('CvoTechnologies/Twitter.Statuses', 'Endpoint');`
to avoid the Error:

> **Unknown repository type "Endpoint". Make sure you register a type before trying to use it.**

But besides that, it works just like a charm.
Nice peace of code :+1:

**Comment by Marlinc** [comment]
That shouldn't be necessary as the Webservice plugin tries to load it before the controller starts. Do you load the bootstrap file when loading the Webservice plugin as shown in the readme?

**Comment by Marlinc** [comment]
A new version has been released that fixes this issue.

**Comment by Marlinc** [comment]
Good to hear that you like it! :+1:

**Comment by agaleski** [comment]
> That shouldn't be necessary as the Webservice plugin tries to load it before the controller starts. 
> That might have been my issue. 

Anyways, I did my composer update and your new version works without any error for me. :)

**Thanks for your quick fix.**
